### ISSUE TITLE
Add Insomnia (By Me)

### ISSUE THREAD

**Issue by talwat** [sainnhe/everforest#103]
Hey! I love your theme.

I made an [insomnia theme for everforest](https://github.com/talwat/insomnia-plugin-everforest-theme), and I was wondering if you could include it.

Thanks again!

**Comment by antoineco** [comment]
@talwat glad to see another port 👍 Feel free to edit the Wiki at https://github.com/sainnhe/everforest/wiki

**Comment by talwat** [comment]
Also, one more thing, is it possible to move the everforest docs to the wiki? It's much easier to read in my opinion.

**Comment by antoineco** [comment]
Probably the installation section should be moved indeed.

These docs are supposed to be opened from inside Vim with `:help everforest`, but to get to this doc you need to install the color scheme.
Chicken and egg problem.

**Comment by talwat** [comment]
Yeah. I suggest maybe moving over troubleshooting and install information over to the wiki but keeping configuration documentation in the text file.

**Comment by antoineco** [comment]
Thanks for updating the wiki 🙌
