### ISSUE TITLE
Wish an option to dim inactive window

### ISSUE THREAD

**Issue by LinoWhy** [sainnhe/everforest#111]
As described, wish this option to identify the active window.

Below is an example using: https://github.com/catppuccin/nvim

![image](https://user-images.githubusercontent.com/43626684/207207482-8870d4f0-f29b-487b-9c4d-31d427ca5166.png)

**Comment by LinoWhy** [comment]
The eob appears to have the same color as inactive window, after enabling this new feature.
![image](https://user-images.githubusercontent.com/43626684/207226510-8a8a10e4-ed2a-4ee0-ba40-26fa221da0e6.png)

**Comment by sainnhe** [comment]
If you don't modify eob:

<img width="1440" alt="截屏2022-12-13 12 30 31" src="https://user-images.githubusercontent.com/37491630/207227008-ec0fe94e-3d16-4f7b-8d87-6472bab9fd97.png">

**Comment by LinoWhy** [comment]
By enabling this option, the highlight EndofBuffer is changed to BufferInactive.
![image](https://user-images.githubusercontent.com/43626684/216880230-b780baa4-943c-4bfc-b77c-bd35a458cafc.png)
This make the eob of current buffer having different color:
![image](https://user-images.githubusercontent.com/43626684/216880887-52c689fe-19d1-4530-85f5-594f44da0428.png)
