### ISSUE TITLE
Updated xfce4-terminal port

### ISSUE THREAD

**Issue by toabr** [sainnhe/everforest#118]
Hi, i wrote an updated version of the xfce4-terminal port for all variants [toabr/everforest-xfce4-terminal](https://github.com/toabr/everforest-xfce4-terminal) ✌️

**Comment by antoineco** [comment]
It looks really nice, thanks for the update! Feel free to add it to the wiki.

**Comment by toabr** [comment]
Thanks!

**Comment by antoineco** [comment]
Closing as done in https://github.com/sainnhe/everforest/wiki/Home/_compare/bc64862%5E...bc64862
