### ISSUE TITLE
neovim in tmux cannot show cursive italics

### ISSUE THREAD

**Issue by ponymushama** [sainnhe/everforest#124]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

macOS Ventura 13.4.1

### Terminal emulator/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

xterm-256color

### Tmux version

tmux 3.3a

### Feature matrix

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {flash.nvim}: unknown key <vscode>

==============================================================================
lazyvim: require("lazyvim.health").check()

LazyVim ~
- OK Using Neovim >= 0.8.0
- OK `git` is installed
- OK `rg` is installed
- OK `fd` is installed
- OK `lazygit` is installed

==============================================================================
noice: require("noice.health").check()

noice.nvim ~
- OK **Neovim** >= 0.8.0
- OK You're using a GUI that should work ok
- OK **vim.go.lazyredraw** is not enabled
- OK **nvim-notify** is installed
- OK **TreeSitter vim** parser is installed
- WARNING **TreeSitter regex** parser is not installed. Highlighting of the cmdline for regex might be broken
- OK **TreeSitter lua** parser is installed
- WARNING **TreeSitter bash** parser is not installed. Highlighting of the cmdline for bash might be broken
- WARNING **TreeSitter markdown** parser is not installed. Highlighting of the cmdline for markdown might be broken
- WARNING **TreeSitter markdown_inline** parser is not installed. Highlighting of the cmdline for markdown_inline might be broken
- OK `vim.notify` is set to **Noice**
- OK `vim.lsp.handlers["textDocument/hover"]` is set to **Noice**
- OK `vim.lsp.handlers["textDocument/signatureHelp"]` is set to **Noice**
- OK `vim.lsp.handlers["window/showMessage"]` is set to **Noice**
- OK `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
- OK `vim.lsp.util.stylize_markdown` is set to **Noice**
- OK `cmp.entry.get_documentation` is set to **Noice**

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /opt/homebrew/Cellar/neovim/0.9.1/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="WezTerm"
- $COLORTERM="truecolor"

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: pbcopy

Python 3 provider (optional) ~
- pyenv: Path: /opt/homebrew/Cellar/pyenv/2.3.23/libexec/pyenv
- pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
- pyenv: Root: /Users/ponymushama/.pyenv
- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- WARNING Could not load Python 3:
  /opt/homebrew/bin/python3 does not have the "neovim" module.
  python3.10 not found in search path or not executable.
  python3.9 not found in search path or not executable.
  python3.8 not found in search path or not executable.
  python3.7 not found in search path or not executable.
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python is Python 2.7 and cannot provide Python 3.
  - ADVICE:
    - See :help |provider-python| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
- Executable: Not found

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v20.5.0
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `notify` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /Users/ponymushama/.local/state/nvim/lsp.log
- Log size: 11612 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: c          ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/c.so
- OK Parser: html       ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: javascript ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/javascript.so
- OK Parser: json       ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: lua        ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: luadoc     ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/luadoc.so
- OK Parser: luap       ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/luap.so
- OK Parser: markdown   ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: python     ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: query      ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/query.so
- OK Parser: regex      ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/regex.so
- OK Parser: tsx        ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/tsx.so
- OK Parser: typescript ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/typescript.so
- OK Parser: vim        ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: yaml       ABI: 13, path: /Users/ponymushama/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: c          ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.1/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.1/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.1/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.1/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.1/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: ` `

### Minimal vimrc that can reproduce this bug.

return {
  -- add colorscheme
  {
    "sainnhe/everforest",
    -- config colorscheme
    config = function()
      vim.g.everforest_enable_italic = 1
      vim.g.everforest_background = "soft"
    end,
  },
  -- Configure LazyVim to load colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "everforest",
    },
  },
}

### Steps to reproduce this bug using minimal vimrc

1. use this Lazyvim colorscheme config to lanch nvim in tmux
2. font is Fisa Code
3. just no cursive italics

### Expected behavior

should show right cursive italics

### Actual behavior

just no cursive italics

**Comment by antoineco** [comment]
This issue is related to `tmux`, not Neovim and/or the colorscheme.

> most display problems are due to **incorrect TERM**
> -- https://github.com/tmux/tmux/wiki/FAQ

By default, `tmux` uses a `screen-256color` TERM for _backwards compatibility reasons_. Unfortunately, the `screen` terminfo doesn't support italics, standout, etc., so you need to set it explicitly to `tmux-256color`.

Likewise, 24-bit True Color (RGB) isn't enabled by default in `tmux`, so you have to enable that terminal feature it explicitly for `termguicolors` to work inside (Neo)Vim, and for your colorschemes to render properly.

Here is a working `.tmux.conf` for you:

```tmux
# https://github.com/tmux/tmux/wiki/FAQ#why-do-you-use-the-screen-terminal-description-inside-tmux
set -g default-terminal 'tmux-256color' # supports italics, standout, etc.

# Enable support for 24-bit true color
# https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour
set -as terminal-features ",xterm-256color:RGB"
```

**Comment by ponymushama** [comment]
> ### Short version (tl;dr)
> * [How to use true colors in vim under tmux? tmux/tmux#1246](https://github.com/tmux/tmux/issues/1246)
> 
> ### Long version
> This issue is related to `tmux`, not Neovim and/or the colorscheme.
> 
> > most display problems are due to **incorrect TERM**
> > -- https://github.com/tmux/tmux/wiki/FAQ
> 
> By default, `tmux` uses a `screen-256color` TERM for _backwards compatibility reasons_. Unfortunately, the `screen` terminfo doesn't support italics, standout, etc., so you need to set it explicitly to `tmux-256color`.
> 
> Likewise, 24-bit True Color (RGB) isn't enabled by default in `tmux`, so you have to enable that terminal feature explicitly for `termguicolors` to work inside (Neo)Vim, and for your colorschemes to render properly.
> 
> Here is a working `.tmux.conf` for you:
> 
> ```shell
> # https://github.com/tmux/tmux/wiki/FAQ#why-do-you-use-the-screen-terminal-description-inside-tmux
> set -g default-terminal 'tmux-256color' # supports italics, standout, etc.
> 
> # Enable support for 24-bit true color
> # https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour
> set -as terminal-features ",xterm-256color:RGB"
> ```
> 
> See also `:h everforest-faq` inside (Neo)Vim, where these `tmux` settings are mentioned.

Thank you for your help. It's so kind.
After adding the code you provided, the question is solved.

But, I have changed the code a little bit to make it work well.

When I first time added your code to my .tmux, there happened a strange thing, my 'zsh-autosuggestions' broke, and typing every letter will show a mess.

```set -g default-terminal 'xterm-256color'```

That's the code I changed.
`tmux-256color` to `xterm-256color`, and then, everything is fine.

**Comment by antoineco** [comment]
Glad it solved the issue!

---

Regarding the terminfo:

I just remembered something about macOS: it ships with an old version of `ncurses` which does not include the `tmux` terminfos.

Here are the terminfos I use with tmux under macOS: https://github.com/antoineco/dotfiles/tree/0f84baff/terminfo
I encourage you to download the two terminfo files there, and run:

```sh
tic -x tmux-256color.terminfo
```
```sh
tic -x xterm-256color.terminfo
```

After this everything should work properly. It does on my Mac, at least.

https://github.com/tmux/tmux/wiki/FAQ explains why `xterm-256color` should only be used by your _terminal emulator_ (the outer terminal), not in tmux (the inner terminal). If you use `xterm-256color` inside tmux, you're going to run into other issues.

**Comment by ponymushama** [comment]
After tic terminfo.
Everything is ok.
Thank a lot.
