### ISSUE TITLE
Additional Low Contrast

### ISSUE THREAD

**Issue by Pantybra** [sainnhe/everforest#125]
I really love the **Everforest** theme. I use it on VS _Codium._ 
For example, to hightlight with red the selected text with this theme is exquisite, and many other details. **Everforest** should be better known. 

Also I like that the normal text is NOT white (dark version). And I would like to be able to adjust the brightness of the normal text, It's this possible? (To further accentuate the low contrast.)

Thanks in advance for attention

**Comment by antoineco** [comment]
Absolutely, you can use a Vim autocmd to change the color of any highlight group.

**Vim**

```vim
" .vimrc

" Apply custom highlights on colorscheme change.
" Must be declared before executing ':colorscheme'.
augroup custom_highlights_everforest
  autocmd!
  " cursorline
  autocmd ColorScheme everforest 
  \       hi Normal guifg=#ffffff
augroup END

colorscheme everforest
```

```lua
-- init.lua (Neovim)

-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_everforest', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'everforest',
  callback = function()
    vim.api.nvim_set_hl(0, 'Normal', { guifg = '#ffffff' })
  end
})

vim.cmd'colorscheme everforest'
```

**Comment by Pantybra** [comment]
I'm in VS Code/_Codium_, how do I access a similar configuration? Maybe editing _settings.json_ file....
It would be great to add that possibility (setting font brightness) to the basic configurations of the extension

**Comment by antoineco** [comment]
Oh, my bad, I didn't get that you were not referring to the Vim color scheme (this repo) but to the VS Code extension.

I am not a VS Code user myself, so only @sainnhe can answer that, but please consider that VS Code is nowhere as configurable as Vim, so your best option is probably to create your own theme in VS Code based on the one you found in the store.

**Comment by sainnhe** [comment]
Sorry for late reply. You can change the color of a token via settings.json, check this doc: https://code.visualstudio.com/api/extension-guides/color-theme

Btw, this repo is for vim/neovim only, so closed since it's unrelated.
