### ISSUE TITLE
Everforest on ImageGoWild to convert images into your palette?

### ISSUE THREAD

**Issue by TheJoin95** [sainnhe/everforest#132]
Hi there,

recently we're making some changes on our project called ImageGoNord, which is basically converting any images/video into any kind of color palette. The project started with the Nordtheme, that's why it's called ImageGoNord, but there is a section called ImageGoWild to collect all the different themes.

Anyway, we saw this issue: https://github.com/Schrodinger-Hat/ImageGoNord/issues/131
Would you like to take it and contribute to the project?

It will enable your community to have something really fast to play with :)

**Comment by antoineco** [comment]
Hi @TheJoin95, nice project but, what is expected from us? The Everforest palette is well documented and colors can be freely picked from it without requesting permission.

I took a look at the txt files for the existing palettes but can't find any documentation for them.

**Comment by TheJoin95** [comment]
About the documentation we were in the process of making it, now it's available at https://github.com/Schrodinger-Hat/ImageGoNord?tab=readme-ov-file#getting-started 

Eventually I believe that in the next month we're going to take the issue posted on the image go nord repo, just to let you know you'll have a tool for easily converting images into your theme :)

If there is anyone willing to contribute on that, feel free to reach out to that issue.

Thank you!
