### ISSUE TITLE
Name of the font in the screenshots?

### ISSUE THREAD

**Issue by hrqmonteiro** [sainnhe/everforest#134]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

n/a

### GUI client/version

n/a

### Feature matrix

n/a

### Minimal vimrc that can reproduce this bug.

n/a

### Steps to reproduce this bug using minimal vimrc

![image](https://github.com/sainnhe/everforest/assets/17055027/393864d8-59ad-4ab6-9af0-2fb2c3ec3a96)

What's the name of this font?

### Expected behavior

n/a

### Actual behavior

n/a

**Comment by antoineco** [comment]
It's a mashup of Monaco and MonoLisa: https://www.sainnhe.dev/post/patch-fonts-with-cursive-italic-styles/

**Comment by hrqmonteiro** [comment]
> It's a mashup of Monaco and MonoLisa: https://www.sainnhe.dev/post/patch-fonts-with-cursive-italic-styles/

Both URLs return 404:

https://git.sainnhe.dev/sainnhe/icursive-nerd-font

https://github.com/sainnhe/icursive-nerd-font

**Comment by antoineco** [comment]
Yes the reason is explained in the first paragraph ("Update 2023...").
