### ISSUE TITLE
Add basic config template in README.md

### ISSUE THREAD

**Issue by Alaz-Oz** [sainnhe/everforest#141]
This theme provides 3 variants:
- hard
- medium (default)
- light

But doesn't seem to provide a way to change to other variant in the README.md

It will make things easier if it provides the config in the README.md

**Comment by antoineco** [comment]
@Alaz-Oz the colorscheme's documentation is self-contained in its Vimdoc: https://github.com/sainnhe/everforest/tree/master/doc

From within (Neo)vim, you can open this documentation with the command `:h everforest` and navigate using Vimhelp key bindings. To jump directly to the background option you were referring to, send the command `:h g:everforest_background`, etc.

**Comment by antoineco** [comment]
I'm closing this issue because the referenced documentation does contain the information requested, including snippets of configuration (and we don't want to conflate README and Vimdoc in the project).
