### ISSUE TITLE
Request to add Delimiter highlights to highlight parenthesis, braces, brackets, etc.

### ISSUE THREAD

**Issue by 231tr0n** [sainnhe/everforest#148]
Hi and thank you for this wonderful colorscheme! I wanted to ask if it was possible to add a config option to highlight Delimiter highlight group so as to highlight parenthesis, braces, brackets, etc with color other than the foreground one.

**Comment by antoineco** [comment]
Adding an option for each and every highlight group is unsustainable and brings little value considering that Vim already allows performing local overrides to colorschemes.

The documentation describes how to perform local customizations using an `autocommand`. Have you checked it out?

**Comment by 231tr0n** [comment]
Yeah i actually checked it out but the thing is i felt like highlighting parenthesis, braces and brackets felt important enough for an extra option to be considered. Yeah I am currently looking into using the auto command for Colorscheme event.

**Comment by antoineco** [comment]
Here is the idiomatic way to do it in Vim:

```vim
augroup EverforestCustom
  autocmd!
  autocmd ColorScheme everforest
  \       hi! Delimiter guibg=#ff0000 guifg=#ffffff gui=bold
augroup END
```

The colors are of course to be adjusted to your liking, and can reference the Everforest as seen in the docs.

I can also share an example for Neovim in case the one in the docs isn't explicit though.

**Comment by 231tr0n** [comment]
I also had one more doubt as to which color can be used for the delimiter group if at all I choose to color it.

**Comment by antoineco** [comment]
You could try linking to Orange or Blue just to get an impression of how things look like.

```vim
augroup EverforestCustom
  autocmd!
  autocmd ColorScheme everforest
  \       hi! link Delimiter Orange
augroup END
```

**Comment by 231tr0n** [comment]
```lua
	vim.api.nvim_create_autocmd("ColorScheme", {
		pattern = "everforest",
		callback = function()
			local config = vim.fn["everforest#get_configuration"]()
			local palette = vim.fn["everforest#get_palette"](config.background, config.colors_override)
			local set_hl = vim.fn["everforest#highlight"]
			set_hl("Search", palette.none, palette.bg_visual_yellow)
		end,
	})
```
I meant from the palette's existing colors. My bad for not being clearer.

**Comment by antoineco** [comment]
You don't need to use `set_hl` if you can link to an existing group like I suggested. All the foreground palette colors already have their own group defined.

**Comment by 231tr0n** [comment]
```lua
	vim.api.nvim_create_autocmd("ColorScheme", {
		pattern = "everforest",
		callback = function()
			local config = vim.fn["everforest#get_configuration"]()
			local palette = vim.fn["everforest#get_palette"](config.background, config.colors_override)
			local set_hl = vim.fn["everforest#highlight"]
			set_hl("@punctuation.bracket", palette.orange, palette.none)
			set_hl("@constructor.lua", palette.orange, palette.none)
		end,
	})
	vim.cmd.colorscheme("everforest")

```
Ok nvm my bad. This blends now
![image](https://github.com/user-attachments/assets/24cce031-02cf-47e0-85aa-663c72ee7689)
Thank you soo much for being patient with me and answering my questions. Means a lot to me. Cheers! I am closing this issue since I have my answer.

**Comment by antoineco** [comment]
Nice!

Just to clarify, I wasn't suggesting that you use the generic Orange as _foreground_ color, but rather that you _link_ to Everforest's Orange highlight group to make your autocmd a bit shorter.

I edited https://github.com/sainnhe/everforest/issues/148#issuecomment-2392059582 with that clarification.
