### ISSUE TITLE
[feature request] make a cosmic dektop everforest theme

### ISSUE THREAD

**Issue by barcell1** [sainnhe/everforest#150]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

linux

### GUI client/version

cosmic

### Feature matrix

..

### Minimal vimrc that can reproduce this bug.

...

### Steps to reproduce this bug using minimal vimrc

...

### Expected behavior

...

### Actual behavior

...

**Comment by antoineco** [comment]
We only maintain the (Neo)vim colorscheme here. All ports are community contributions and can be added here: https://github.com/sainnhe/everforest/wiki
