### ISSUE TITLE
Base16 support

### ISSUE THREAD

**Issue by jef** [sainnhe/everforest#40]
### Description

We should build out a base16 scheme for all three variants of Dark and Light.

### Possible solution

Here is the spec: https://github.com/chriskempson/base16/blob/master/styling.md

This is a good example of what it could look like: https://github.com/dawikur/base16-gruvbox-scheme

**Comment by sainnhe** [comment]
The color palette has changed a lot in recent commits, and it's not fully finished yet, there may be some new improvements in the future.

Let's not create base16 for now, wait until a new version is released.

Btw, what do you think of the light variant? Is the contrast enough?

And do you prefer the new dark variant now compared to what it is before? I made the background color a bit darker, but I think it's somewhat too green now.

**Comment by jef** [comment]
I'm really liking the light version, I think it was well done. I'm sure you'll find some tuning there, but overall looks great.

As for the Hard, Medium, and Soft versions; I see the difference, but it's seems so minor that I feel like it's not enough to switch between the three. Especially between Medium and Soft.

That being said, I don't know how dramatic you'd like to take in each direction.

https://camo.githubusercontent.com/e814989a4842426cbafd88f51cc7f4e0ebc9a211b57ec5709b127a090fb20065/687474703a2f2f692e696d6775722e636f6d2f354d53626536542e706e67

With here, we can see quite a bit of difference between each one. Not sure if it's perspective (since all together), but it seems that the lightness scale is more dramatic.

**Comment by sainnhe** [comment]
Thanks for your suggestion, yeah it's necessary to adjust the background color, I'm going to do it later.

**Comment by sainnhe** [comment]
Done. You can update this color scheme and get it a try.

**Comment by Smeeba** [comment]
I like the new light theme, I think its great! I don't think that the dark theme's background is too green, though I did like the old forest-dusk variant. If you think that's very green, your head would probably pop off if you saw the [Cave of the Past](https://raw.githubusercontent.com/benbusby/earthbound-themes/main/images/demos/cave_of_the_past.png) theme from the [Earthbound Themes](https://github.com/benbusby/earthbound-themes) project.

**Comment by sainnhe** [comment]
@Smeeba Yeah, thanks, I'm feeling good after I get used to the new dark variant. I think the forest dusk variant is unnecessary because you can use programs like redshift to adjust the color temperature, which is much more convenient, so I directly removed it.

**Comment by sainnhe** [comment]
@jef I think the current color palette is usable enough so I released a new version.

I just tried to create a template file, but I haven't successfully built a scheme via the base16 builder yet.

https://gist.github.com/sainnhe/3298202006955aab02c77fb01c279298

**Comment by sainnhe** [comment]
And another question is that how should we maintain the base16 schemes?

Should we just put the yaml files in this repo or create a new repo?

Should we create a PR in the upstream repo?

And who is going to maintain the base16 schemes? I personally don't have much time so I think it would be better if someone else could take it over.

**Comment by jef** [comment]
Great start. I don't mind maintaining it as long as the colors look good to you. I take a look at it when I'm back from vacation!

**Comment by sainnhe** [comment]
@jef Thank you! Wish you to have a happy vacation ;)

**Comment by zakrywilson** [comment]
I would really like to have this theme in base16's repo as well 👍

**Comment by jef** [comment]
Base16 is basically abandoned at this point. I don't think this will happen anymore.

**Comment by antoineco** [comment]
@AgingOrange the original author emerged back from nowhere just to literally delete the entire Git history, then went dormant again.

See https://github.com/base16-project/home/issues/51 for some context about where the reboot of the base16 project is heading.

**Comment by antoineco** [comment]
FYI Everforest made its way into the Base16 reboot project from an old PR (deleted by the author like everything else), but some colors seem outdated (`#3a4248`, `#868d80`, `#a59572`): [base16-schemes/everforest.yaml](https://github.com/base16-project/base16-schemes/blob/99529527e7cb3d777fb6e041c2aabbe6cdec4c4c/everforest.yaml)

![base16-everforest](https://user-images.githubusercontent.com/3299086/185096976-0a8f40c7-6b07-4c52-b249-0311bb484898.png)

Ref. https://github.com/base16-project/base16-schemes/pull/1

**Comment by antoineco** [comment]
The theme made it downstream so I'm going to go ahead and close this as resolved.

The issue with outdated colors is being tackled downstream in https://github.com/base16-project/base16-schemes/issues/13.
