### ISSUE TITLE
[Breaking change] Rename color scheme from Forest Night to Everforest

### ISSUE THREAD

**Issue by sainnhe** [sainnhe/everforest#43]
# Why?

This color scheme was created at my early stage, at that time it was basically a mixture of [rhysd/vim-color-spring-night](https://github.com/rhysd/vim-color-spring-night) and [karoliskoncevicius/sacredforest-vim](https://github.com/karoliskoncevicius/sacredforest-vim), so I simply gave it the name "forest-night".

But now the situation has changed. The dark variant is not only based on spring night and sacredforest, but also based on my another color scheme [gruvbox-material](https://github.com/sainnhe/gruvbox-material) (inspired by [morhetz/gruvbox](https://github.com/morhetz/gruvbox)). More importantly, I recently designed a new light variant based on solarized, which makes the name sounds strange.

Therefore, I believe it is necessary to rename this color scheme, even though people may need to update their vimrc to get it work.

Sincere apologies for the inconvenience caused.

# How to update my vimrc?

**Step1.**

Replace `forest-night` and `forest_night` with `everforest`, like this:

```vim
" Old
set background=dark
let g:forest_night_enable_italic = 1
let g:forest_night_disable_italic_comment = 1
colorscheme forest-night
let g:lightline.colorscheme = 'forest_night'


" New
set background=dark
let g:everforest_enable_italic = 1
let g:everforest_disable_italic_comment = 1
colorscheme everforest
let g:lightline.colorscheme = 'everforest'
```

**Step2.**

Remove `$INSTALL_PATH/doc/tags`, and regenerate it via this command:

```vim
:helptags /path/to/everforest/doc/
```

**Step3.**

If you have `g:forest_night_better_performance` enabled, you'll also need to remove the syntax files generated by forest-night.

Typically, these files are located in `$INSTALL_PATH/after/ftplugin`. You can simply remove this directory, then it will be regenerated with updated code.

**Comment by talwat** [comment]
Hasn't this been resolved?

**Comment by antoineco** [comment]
Yes, but closing would unpin the issue.

**Comment by sainnhe** [comment]
Closed since this issue has been pinned for over 1 year.
