### ISSUE TITLE
Switching to a different theme from this one is breaking syntax.

### ISSUE THREAD

**Issue by mrillusi0n** [sainnhe/everforest#44]
- OS: macOS 10.15.7
- Terminal: Kitty 0.19.3
- `echo $TERM`: xterm-kitty
- `nvim --version`: 0.4.4

Sourcing the `init` file with a different theme (`ayu` in this example).
![image](https://user-images.githubusercontent.com/37063502/111911193-823ba900-8a8a-11eb-88c5-f54541ac6248.png)

Switch to `everforest`
![image](https://user-images.githubusercontent.com/37063502/111911230-ad25fd00-8a8a-11eb-962d-73036b4418a2.png)

Switch back to `ayu` (Broken Syntax)
![image](https://user-images.githubusercontent.com/37063502/111911265-d9417e00-8a8a-11eb-9935-3dbb289e7d7c.png)

Breaks it for all the other ones too.

**Comment by sainnhe** [comment]
https://github.com/sainnhe/everforest/blob/2dd7dd9e96992f80596603807f9254f8d4ef90dd/doc/everforest.txt#L334-L337

It's a bug of nvim, can't fix in color scheme level.

**Comment by sainnhe** [comment]
https://github.com/vim/vim/issues/4405

To fix this issue, execute `syntax on` before switching color schemes.

**Comment by andymass** [comment]
This should be fixed in neovim as of https://github.com/neovim/neovim/pull/14060
