### ISSUE TITLE
Enable bold

### ISSUE THREAD

**Issue by frandsoh** [sainnhe/everforest#45]
### Description

I'd like to have to option to enable bold - like in your Gruvbox Material colorscheme (which I've used exclusively for the last months. Thank you ❤️ - Time for a change )

### Possible solution

The same as in Gruvbox Material - I guess 😄

**Comment by sainnhe** [comment]
Sorry but I'm not interested in this feature. I added enable_bold option in gruvbox material simply because the original gruvbox support it, but I personally never use it.

PR is welcome.

**Comment by frandsoh** [comment]
That's alright - might take a look at it 👍 
Thanks again for making great colorschemes.
