### ISSUE TITLE
Sublime Text support

### ISSUE THREAD

**Issue by graducan** [sainnhe/everforest#47]
Please add support for Sublime Text [https://www.sublimetext.com/](url)

**Comment by sainnhe** [comment]
Someone has already ported it to sublime https://github.com/sainnhe/everforest/wiki

**Comment by graducan** [comment]
@sainnhe only the dark option is available and the generator that was used does not work anymore..

**Comment by sainnhe** [comment]
https://github.com/sainnhe/everforest/blob/95110894cddf4663b871e2ca231e10e196899ed8/doc/everforest.txt#L464-L470

---

I don't use sublime, if you're not satisfied with that port, you can create one by yourself.

**Comment by avelican** [comment]
late reply but https://github.com/avelican/everforest-sublime
Converted automatically from https://github.com/sainnhe/everforest-vscode using https://github.com/tobiastimm/code-theme-converter
