### ISSUE TITLE
An option to disable underlining?

### ISSUE THREAD

**Issue by theteachr** [sainnhe/everforest#50]
![image](https://user-images.githubusercontent.com/64728420/126846299-748e6c00-401a-42fd-9994-005a8c80c572.png)
I find those underlines distracting, and would like to disable the same.

```vim
let g:everforest_disable_underline = 1
```

**Comment by sainnhe** [comment]
I can't reproduce, please follow the [issue template](https://raw.githubusercontent.com/sainnhe/everforest/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide detailed information.

**Comment by sunaku** [comment]
@theteachr - Perhaps this is the same as issue #46?

**Comment by theteachr** [comment]
@sunaku, thanks! I can do with the  workaround mentioned in #46.
