### ISSUE TITLE
JS/TS: No differentiation between template literal placeholders and normal strings

### ISSUE THREAD

**Issue by benfrain** [sainnhe/everforest#51]
- Operating system/version: macOS 11.5.2
- Terminal emulator/version:
- `echo $TERM`: xterm-kitty
- `vim --version` or `nvim --version`: 

```
NVIM v0.6.0-dev+1607-g7d2233fad
```

### Steps to reproduce this bug using minimal vimrc
Use template literal in JS with this inside:

```
`<div
  expression=${this.dataLoader.payload?.markets}
  quote="{this.dataLoader.payload?.participants}"
  ></div>
            `
```

### Actual behaviour
Here is a grab from everforest:
![image](https://user-images.githubusercontent.com/1318466/129350234-94ae73d6-8e74-4561-b26b-6f0b57c00ec0.png)

### Expected behaviour
Here is a grab from Sublime text (notice the different treatment of the expression):
![image](https://user-images.githubusercontent.com/1318466/129350161-e1f80d2a-d130-4331-9acd-875da1730c04.png)

**Comment by benfrain** [comment]
Actually, the problem may merely be with treesitter in general as same issue exists with other schemes. It actually seems to be  with [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates)

Here is a js/ts reduction to illustrate:

```javascript
let info = "test";
const test = `<div 
    data-expression=${info}
    data-string="{info}"
</div>
`;

return html`
    <div
    data-expression=${info}
    data-string="{info}"
    ></div>
`;

In the tagged template literal, nvim seems to treat those to things the same, whereas the standard template literal they are treated correctly.
```

**Comment by sainnhe** [comment]
Looks like it's a bug of vim syntax plugin or tree-sitter, I'm not sure if it can be fixed in color scheme level.

A color scheme generally colors the scope provided by syntax files or tree-sitter, if they can't parse things like tagged template literals, then it can't be colored.

**Comment by benfrain** [comment]
@sainnhe thanks, opened a bug over on Tree Sitter repo: https://github.com/nvim-treesitter/nvim-treesitter/issues/1688
Love this theme BTW 👍
