### ISSUE TITLE
Name of the font from the screenshot in the README

### ISSUE THREAD

**Issue by ceoshikhar** [sainnhe/everforest#52]
Hey,

I really liked the font used in the demo of the color scheme from the README.md and I would really appreciate it if you could tell me the name of it.

Thank you.

**Comment by sainnhe** [comment]
https://github.com/sainnhe/everforest/blob/a82fc25c786799c7d3c8ca771c6bf2690cc214a5/doc/everforest.txt#L477-L483

I built all these fonts for archlinux, you can download the tarballs here and extract them: https://github.com/sainnhe/repo/tree/master/archlinux/x86_64
