### ISSUE TITLE
Color scheme port for ITerm2

### ISSUE THREAD

**Issue by VitalyPetrov** [sainnhe/everforest#54]
Everforest looks to be a perfect theme for terminal emulator.
Could you please provide a port of this theme to ITerm2?

**Comment by sainnhe** [comment]
Some have already ported it to iterm2, check related projects: https://github.com/sainnhe/everforest/wiki

Also you can use my personal dotfiles: https://github.com/sainnhe/dotfiles/tree/master/.macos/iTerm2
