### ISSUE TITLE
IDEA support

### ISSUE THREAD

**Issue by TENX-S** [sainnhe/everforest#61]
I love this theme so bad !!!

**Comment by sainnhe** [comment]
Thanks for your appreciation :)

There'a already a port by @jef , check the [wiki page](https://github.com/sainnhe/everforest/wiki).

**Comment by jef** [comment]
It could use some love with the new variations! Thanks @sainnhe.

**Comment by francma** [comment]
There is also Jetbrains theme created by me - https://github.com/francma/everforest-jetbrains. It is still a work in progress, only some languages are supported and UI theme can look broken (especially the light variant).
