### ISSUE TITLE
lsp hover window background improvement?

### ISSUE THREAD

**Issue by xfyuan** [sainnhe/everforest#65]
First thank you for the great colorscheme for Vim/Neovim! I've used it more than 2 years. 👍

Maybe there's an improvement for its lsp hover window's effect?

The default hover document window looks like this:

<img width="956" alt="截屏2022-04-29 00 02 30" src="https://user-images.githubusercontent.com/5710838/165797059-55936f68-0550-48e3-8aef-acf5877cceca.png">

There's some place between the border and the background color area, it's not so good, I think.

After some research, I found we can set the `NormalFloat` background to none to solve that problem. The code position is:

https://github.com/sainnhe/everforest/blob/1e594a20ce382bcc55c0e3fd488e90ca68dffb32/colors/everforest.vim#L130

And the new result is like this:
<img width="959" alt="截屏2022-04-29 00 01 48" src="https://user-images.githubusercontent.com/5710838/165797790-6c3e9ce6-4eed-499e-a6c2-06d8e172c50c.png">

Does it looks better?

**Comment by sainnhe** [comment]
Does https://github.com/sainnhe/everforest/commit/f748681a3fac2496aedf694f5bd09a30f80cd3c0 fix this issue for you?

**Comment by xfyuan** [comment]
I just updated to the latest version, found it looks like this now:

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/5710838/166703927-56aeb2b5-e7f5-4978-b347-4c35095cd7f4.png">

I thinks it's better than before. But as my own opinion, I like the hover window without the bg2 background color more than above version:)

**Comment by xfyuan** [comment]
Any way, current version is better than old one. Thank you. Maybe this issue can be closed unless anyone has other thought about it.
