### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by J3imip** [sainnhe/everforest#66]
Is there any ways to get rid of the color scheme background color? ![image](https://user-images.githubusercontent.com/62905303/168915581-7bd262be-abc5-4beb-8af4-31456dff5dc4.jpeg)

how you can see background of the terminal and neovim is different because of transparency of my command line

**Comment by sainnhe** [comment]
Do you mean this?

https://github.com/sainnhe/everforest/blob/f748681a3fac2496aedf694f5bd09a30f80cd3c0/doc/everforest.txt#L252-L262

**Comment by J3imip** [comment]
> Do you mean this?
> 
> 
> 
> https://github.com/sainnhe/everforest/blob/f748681a3fac2496aedf694f5bd09a30f80cd3c0/doc/everforest.txt#L252-L262

Absolutely. Warmest thanks!
