### ISSUE TITLE
How can configure my plugin?

### ISSUE THREAD

**Issue by Villelmo** [sainnhe/everforest#68]
I follow the steps but i don't get any result. 

When open a new file from VIM the color sheme is the default. I trying to configure the color scheme **everforest** but the color not change.

**Comment by antoineco** [comment]
@Villelmo apologies for the long response time. By now you probably figured out how to install color schemes for Vim, but just in case, here is a short guide.

---

If you are using Vim (not Neovim), configurations go into a file called `.vimrc` inside your home directory. If it doesn't exist, simply create it.

You need to add those lines at the end of the configuration file:

```vim
set termguicolors
set background=dark  " or light for the light variant
colorscheme everforest
```

This assumes that the Everforest color scheme is installed. With Vim (not Neovim) the simplest way to do that is to clone this Git repository inside `~/.vim/pack/myplugins/start/everforest`.
