### ISSUE TITLE
Comment text color is black on white background

### ISSUE THREAD

**Issue by Trikenstein** [sainnhe/everforest#79]
### Operating system/version

Ubuntu 22.04

### Terminal emulator/version

Gnome terminal 3.44.0 Gnome 42

### $TERM environment variable

screen-256color

### Tmux version

tmux 3.2a

### Feature matrix

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)
Included patches: 1-3995
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-8W0Acv/vim-8.2.3995=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lsodium -lacl -lattr -lgpm -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -ldl -lm -lm 

### Minimal vimrc that can reproduce this bug.

set hlsearch
set incsearch
set ignorecase
set number
set nowrap

" 2 lines above/below cursor when scrolling"
set scrolloff=2

" Show matching brackets when text indicator is over them"
set showmatch
" How many 1/10 second to blink when matching brackets"
set matchtime=2

" show mode in status bar (insert/replace/...)"
set showmode

" show typed command in status bar"
set showcmd

" show cursor position in status bar"
set ruler

" show file in titlebar"
set title

" regex search pattern: change the way backslashes are used in search patterns"
set magic

" keep 50 lines of command history"
set history=50

" use mouse in visual mode (not normal,insert,command,help mode"
set mouse=v

" Add a bit extra margin to the left"
set foldcolumn=1

set laststatus=2
" Format the status line"
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c

" completion with menu"
set wildmenu

"------------------------------------------------------------"
" editing behaviors"
"------------------------------------------------------------"
" tabstop:          Width of tab character"
" softtabstop:      Fine tunes the amount of white space to be added"
" shiftwidth        Determines the amount of whitespace to add in normal mode"
" expandtab:        When this option is enabled, vi will use spaces instead of tabs"
set tabstop     =2
set softtabstop =2
set shiftwidth  =2
set expandtab
"enable backspace in insert mode"
set backspace=indent,eol,start

"autoindent: next line same indent as prev, smartindent: may add indent depending on language"
set autoindent

" No annoying sound on errors"
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Visual mode pressing * or # searches for the current selection"
vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>

"Disable Ctrl-Z (in normal mode)"
nnoremap <C-z> ""

"------------------------------------------------------------"
" visual & look"
"------------------------------------------------------------"
set background=dark
"colorscheme OceanicNext
colorscheme everforest
syntax on
set t_Co=256

"--vim-airline theme: https://github.com/vim-airline/vim-airline" let g:airline_theme='onedark'

"------------------------------------------------------------"
" file types, languages"
"------------------------------------------------------------"
augroup filetypedetect
  au BufNewFile,BufRead *.sc set filetype=scala syntax=scala
  au BufNewFile,BufRead *.cql set filetype=sql syntax=sql
  au BufNewFile,BufRead *.jsonc set filetype=json syntax=json
augroup END

" Ignore files"
set wildignore=*.o,*~,*.pyc
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store

"------------------------------------------------------------"
" When opening & saving: replace \t by 2 spaces, delete trailing spaces"
" * means all file types"
" The substitution commands will add their patterns to your search history and since this happens for each file load and save you might be bothered by it. If so, :keeppatterns will prevent it. Insert keepp before each substitution"
" * means all file types, silent=don't display feedback, /ge means global and don't raise error if there was no substitution"
"------------------------------------------------------------"
augroup SpaceFix
  autocmd!
  autocmd BufReadPost,BufWritePre * :keeppatterns %s/\s\+$//ge | :keeppatterns %s/\t/  /ge
augroup END

"------------------------------------------------------------"
" Helper functions"
"------------------------------------------------------------"

" Returns true if paste mode is enabled"
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    endif
    return ''
endfunction

" Don't close window, when deleting a buffer"
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif

    if bufnr("%") == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute("bdelete! ".l:currentBufNum)
    endif
endfunction

function! CmdLine(str)
    call feedkeys(":" . a:str)
endfunction

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", "\\/.*'$^~[]")
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'gv'
        call CmdLine("Ack '" . l:pattern . "' " )
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction

### Steps to reproduce this bug using minimal vimrc

```
vim ~/.vimrc
```

Or open any JSON, SH, YAML file having comments

### Expected behavior

Wish the comment color doesn't have a white background

### Actual behavior

comments written in black on white background. See desired syntax colors in a close enough color theme [OceanicNext](https://github.com/rafi/awesome-vim-colorschemes)

![everforest_comment_black-on-white](https://user-images.githubusercontent.com/72353094/184794992-6b1a8cec-e357-45bf-b713-6cfdf616579d.png)

![OceanNext_Vim-color](https://user-images.githubusercontent.com/72353094/184795015-c4373eee-0a22-4f27-9d33-124b6dbca33d.png)

**Comment by sainnhe** [comment]
Maybe try to disable italics in comments?

https://github.com/sainnhe/everforest/blob/33e83efc6f4cb9cd4f16354ad53dac691e844c3f/doc/everforest.txt#L484-L491

**Comment by Trikenstein** [comment]
Where do these italic come from?

**Comment by sainnhe** [comment]
Read the help doc, these is an option to do so.

**Comment by Trikenstein** [comment]
Fixed, add this in `~/.vimrc`

```
let g:everforest_disable_italic_comment = 1
```

Not sure how many time you received this kind of request. May be reverse the default option to NOT use italic? And only leave the option only for the experts who really want itaclic and who know how to enable that italic option?

In anyway, thanks for this awesome VIM color theme. Discovered it today in https://vimcolorschemes.com/ right in the front page.

**Comment by sainnhe** [comment]
Why italics comments should be disabled by default? Italic comments is widely used in not only vim color schemes, but also other editor themes (vscode, atom, sublime text, etc.), it's a commonly used design.

Secondly, even if italics are not used in comments, italics are also widely use in other parts (keywords, types, variables, etc.). With fonts that have cursive italics like Operator Mono, we can get a very cool UI. This design is by default in many neovim color schemes.

More importantly, why should I remove a feature because of a bug caused by other apps?

> Not sure how many time you received this kind of request.

Actually not many, because this bug only exists in very limited number of terminal emulators, so far as I know there are gnome terminal, urxvt, and the built-in terminal emulator of macOS. So I think adding an FAQ should be enough.

**Comment by antoineco** [comment]
I think the problem here is the usage of `tmux` (or `screen`?), not the terminal emulator itself.

To support italics in modern tmux versions, you need to set the correct terminfo inside your tmux configuration:

```
set -g default-terminal 'tmux-256color'
```

**Comment by sainnhe** [comment]
Maybe you need this:

https://github.com/sainnhe/everforest/blob/33e83efc6f4cb9cd4f16354ad53dac691e844c3f/doc/everforest.txt#L457-L459

**Comment by Trikenstein** [comment]
Applied the tricks shown in https://github.com/tmux/tmux/issues/1246
In particular, added this in .vimrc

```
if (has("termguicolors"))
  set termguicolors
endif
```

VIM 8.2 has lost all syntax colors. Disabling the above lines and colors came back. My ~/.tmux.conf alread had `set -g default-terminal "screen-256color"`. Changing to 

```
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
```
Makes no differences. 

Overall, a lots of headaches just to have italic fonts in the terminal. Which fortunately I can live without.

**Comment by antoineco** [comment]
`set -g default-terminal "screen-256color"` will definitely not work. See my previous comment.

**Comment by Trikenstein** [comment]
@antoineco FANTASTIC! setting in `tmux.conf` 

```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
```

and adding in `~/.vimrc` 

```
if exists('+termguicolors')
  if &term =~ "tmux"
    let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
    let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
  endif

  set termguicolors
endif
```
Now enables italics in comments! Not sure if this is really a revolution but at least I am happy that my tmux config is behaving correctly. Thanks.

**Comment by antoineco** [comment]
You're welcome! I've had my fair share of struggles getting modern terminal applications to work properly with tmux, so I can relate 😅
